### ISSUE TITLE
Mod does not work on 1.19.2 servers! [Fatal]

### ISSUE THREAD

**Issue by crispeeweevile** [RuochenFu21/CreateMoreDrillHeads#10] opened 2023-11-29 23:57 UTC
**Short summary:**
The mod does not work at all on Forge 1.19.2-43.3.2 and does not allow the server to start. It does work on the Minecraft Forge client side. I can start, and play on worlds, but you can't host a dedicated server with it.

**Problem:**
Mod fails to load on dedicated 1.19.2-43.3.2 Forge servers.
**Expected:**
The mod to load correctly on most (all) 1.19.2 Forge servers.
**Mod list:**
create-1.19.2-0.5.1.f
createmodedrillheads-2.0.2-1.19.2
**log:**
https://pastebin.com/CXeqmWry

Thanks in advance.

**Comment by furuochen-dev** [comment] 2023-11-30 01:36
I think can confirm

**Comment by crispeeweevile** [comment] 2023-11-30 01:38
> I think can confirm

Any chance you know when this'll get fixed?

**Comment by furuochen-dev** [comment] 2023-11-30 11:00
> > I think can confirm
> 
> Any chance you know when this'll get fixed?

When I got time

**Comment by crispeeweevile** [comment] 2023-12-01 09:27
> > > I think can confirm
> > 
> > 
> > Any chance you know when this'll get fixed?
> 
> When I got time

That's fair, I was just hoping to add it to my server since it's a really cool mod, but I'll just have to wait until you have time, thanks for the help 🙂

**Comment by furuochen-dev** [comment] 2024-02-02 11:40
Possibly be duplicate of #11

**Comment by furuochen-dev** [comment] 2024-02-13 09:19
Fixed in 2.0.3

**Closed as completed by furuochen-dev** 2024-02-13 09:19 UTC
