### ISSUE TITLE
Crash on Arclight due to NoClassDefFoundError

### ISSUE THREAD

**Issue by GLDYM** [RuochenFu21/CreateMoreDrillHeads#5] opened 2023-09-07 07:16 UTC
When loading this mod on arclight with create-0.5.1c,  the server crashed; but it didn't cause crash on client side. I think the crash was caused by this mod but not arclight.
Here is the crash-report.
[crash-2023-09-07_15.06.19-fml.txt](https://github.com/RuochenFu21/CreateMoreDrillHeads/files/12545834/crash-2023-09-07_15.06.19-fml.txt)

**Comment by furuochen-dev** [comment] 2023-09-08 01:33
this could be a problem with arclight

**Comment by furuochen-dev** [comment] 2023-09-08 01:33
Is this your first time initialising the game?

**Comment by furuochen-dev** [comment] 2023-09-08 01:34
Maybe try load without arclight

**Comment by GLDYM** [comment] 2023-09-08 10:37
> Maybe try load without arclight

It's the first time initialising the game. When loading without arclight, it crashed too.
[crash-2023-09-08_18.35.42-fml.txt](https://github.com/RuochenFu21/CreateMoreDrillHeads/files/12558512/crash-2023-09-08_18.35.42-fml.txt)

**Comment by furuochen-dev** [comment] 2023-09-08 15:11
Mod version, create mod version, minecraft version pls

**Comment by GLDYM** [comment] 2023-09-09 13:43
> Mod version, create mod version, minecraft version pls

All the information shows in the crash-report.
Mod version: 1.18.2-v2.0.2
create mod version: 0.5.1c

**Comment by furuochen-dev** [comment] 2023-09-09 13:44
Hm

**Comment by furuochen-dev** [comment] 2023-09-09 13:44
What mod you have except for this one

**Comment by GLDYM** [comment] 2023-09-09 13:45
> What mod you have except for this one

None

**Comment by furuochen-dev** [comment] 2023-09-09 13:46
Check if creating a separate world on client crashes the game too

**Comment by GLDYM** [comment] 2023-09-09 13:47
It doesn't crash on client side.
I think the game crash because of using a class that not existing on the server side, as the crash-report shows.

**Comment by furuochen-dev** [comment] 2023-09-09 13:49
Just checkin', because I do think I fixed this on v1.3

**Comment by furuochen-dev** [comment] 2023-09-09 13:50
Welp I think I'll try to fix this the next time I update this mod

**Comment by furuochen-dev** [comment] 2024-02-02 11:43
Could also be a duplicate of #11

**Comment by furuochen-dev** [comment] 2024-02-13 09:19
Fixed in 2.0.3

**Closed as completed by furuochen-dev** 2024-02-13 09:19 UTC
