### ISSUE TITLE
Crashes during 1.20.1 boot

### ISSUE THREAD

**Issue by BlankGopher** [RuochenFu21/CreateMoreDrillHeads#9] opened 2023-10-27 15:29 UTC
[2023-10-27-2.log](https://github.com/RuochenFu21/CreateMoreDrillHeads/files/13190744/2023-10-27-2.log)

Either the issue is with the mod or it's incompatible with another mod. Removing the *Create: More Drill Heads* mod allows the modpack to boot with no apparent issues.

**Comment by furuochen-dev** [comment] 2023-10-28 12:57
Duplicate of #8

**Closed as completed by furuochen-dev** 2023-10-28 12:57 UTC
