### ISSUE TITLE
1.20.1 Version 2.0.2 doesn't work on dedicated forge server version 1.20.1-47.2.0

### ISSUE THREAD

**Issue by 0rangy** [RuochenFu21/CreateMoreDrillHeads#11] opened 2024-01-04 15:41 UTC
While loading up, the mod throws:

java.lang.ClassNotFoundException: net.minecraft.client.renderer.blockentity.BlockEntityRenderer

caused because servers don't have net.minecraft.client because it's a server.

**Comment by shiosakun** [comment] 2024-01-17 01:31
I'm having exactly the same problem... Here is my crash report 

17.01 01:24:11 [Server] INFO ---------------------------------------------------------------------------------------
17.01 01:24:11 [Server] INFO -- Head --
17.01 01:24:11 [Server] INFO Thread: main
17.01 01:24:11 [Server] INFO Suspected Mods: NONE
17.01 01:24:11 [Server] INFO Stacktrace:
17.01 01:24:11 [Server] INFO 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
17.01 01:24:11 [Server] INFO -- MOD createmoredrillheads --
17.01 01:24:11 [Server] INFO Details:
17.01 01:24:11 [Server] INFO 	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/blockentity/BlockEntityRenderer
17.01 01:24:11 [Server] INFO 		at com.forsteri.createmoredrillheads.core.DrillTierRegisterer.initDrill(DrillTierRegisterer.java:28) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 		at com.forsteri.createmoredrillheads.core.DrillTierRegisterer.<init>(DrillTierRegisterer.java:19) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 		at com.forsteri.createmoredrillheads.entry.TieredDrillRegistration.lambda$static$0(TieredDrillRegistration.java:35) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at com.forsteri.createmoredrillheads.entry.TieredDrillRegistration.<clinit>(TieredDrillRegistration.java:29) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 		at com.forsteri.createmoredrillheads.CreateMoreDrillHeads.<init>(CreateMoreDrillHeads.java:25) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.19.jar%23231!/:?] {}
17.01 01:24:11 [Server] INFO 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.19.jar%23230!/:?] {}
17.01 01:24:11 [Server] INFO 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
17.01 01:24:11 [Server] INFO 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	Mod File: /mods/createmoredrillheads-2.0.2-1.20.1.jar
17.01 01:24:11 [Server] INFO 	Failure message: Create: More Drill Heads (createmoredrillheads) has failed to load correctly
17.01 01:24:11 [Server] INFO 		java.lang.NoClassDefFoundError: net/minecraft/client/renderer/blockentity/BlockEntityRenderer
17.01 01:24:11 [Server] INFO 	Mod Version: 2.0.2-1.20.1
17.01 01:24:11 [Server] INFO 	Mod Issue URL: NOT PROVIDED
17.01 01:24:11 [Server] INFO 	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.blockentity.BlockEntityRenderer
17.01 01:24:11 [Server] INFO Stacktrace:
17.01 01:24:11 [Server] INFO 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
17.01 01:24:11 [Server] INFO 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at com.forsteri.createmoredrillheads.core.DrillTierRegisterer.initDrill(DrillTierRegisterer.java:28) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 	at com.forsteri.createmoredrillheads.core.DrillTierRegisterer.<init>(DrillTierRegisterer.java:19) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 	at com.forsteri.createmoredrillheads.entry.TieredDrillRegistration.lambda$static$0(TieredDrillRegistration.java:35) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at com.forsteri.createmoredrillheads.entry.TieredDrillRegistration.<clinit>(TieredDrillRegistration.java:29) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 	at com.forsteri.createmoredrillheads.CreateMoreDrillHeads.<init>(CreateMoreDrillHeads.java:25) ~[createmoredrillheads-2.0.2-1.20.1.jar%23180!/:2.0.2-1.20.1] {re:classloading}
17.01 01:24:11 [Server] INFO 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.19.jar%23231!/:?] {}
17.01 01:24:11 [Server] INFO 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.19.jar%23230!/:?] {}
17.01 01:24:11 [Server] INFO 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
17.01 01:24:11 [Server] INFO 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
17.01 01:24:11 [Server] INFO -- System Details --
17.01 01:24:11 [Server] INFO Details:
17.01 01:24:11 [Server] INFO 	Minecraft Version: 1.20.1
17.01 01:24:11 [Server] INFO 	Minecraft Version ID: 1.20.1
17.01 01:24:11 [Server] INFO 	Operating System: Linux (amd64) version 4.19.0-11-amd64
17.01 01:24:11 [Server] INFO 	Java Version: 17.0.1, Oracle Corporation
17.01 01:24:11 [Server] INFO 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation

**Comment by TrevorAC99** [comment] 2024-01-27 19:57
I'm having roughly the same issue on Minecraft 1.18, mod version 2.0.2

**Comment by furuochen-dev** [comment] 2024-01-31 00:34
Log pls

**Comment by furuochen-dev** [comment] 2024-02-13 09:19
Fixed in 2.0.3

**Closed as completed by furuochen-dev** 2024-02-13 09:19 UTC
